# ===========================
# PostgreSQL (Neon Database)
# ===========================

spring.datasource.url=jdbc:postgresql://ep-morning-tooth-aypjkubj-pooler.c-5.us-east-2.aws.neon.tech/neondb

spring.datasource.username=neondb_owner

spring.datasource.password=npg_BOluwnHbYy05

spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# Thymeleaf
# ===========================

spring.thymeleaf.cache=false

# ===========================
# Server
# ===========================

server.port=8080

# ===========================
# Gmail Mail Configuration
# ===========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=goudasanikarunakar95@gmail.com
spring.mail.password=lavs kkfb cocy khjq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000